# .travis.yml
# This file should be at the root of your project
language: node_js
cache: 
  yarn: true
  directories:
    - ~/.npm
    - node_modules
node_js:
  - '8'
before_install:
  - npm i -g docusaurus-init
script:
  - cd website
  - npm run publish-gh-pages
branches:
  only:
    # Change this to gh-pages if you're deploying using the gh-pages branch
    - master