# .travis.yml
# This file should be at the root of your project
language: node_js
cache: 
  yarn: true
  directories:
    - ~/.npm
    - node_modules
node_js:
  - '8'
before_install:
  - npm i -g docusaurus-init
script:
  - git config --global user.name "liuzhenqi77"
  - git config --global user.email "liuzhenqi77@users.noreply.github.com"
  - echo "machine github.com login liuzhenqi77 password ${GITHUB_TOKEN}" >~/.netrc
  - cd website && npm install && GIT_USER=liuzhenqi77 npm run publish-gh-pages
branches:
  only:
    # Change this to gh-pages if you're deploying using the gh-pages branch
    - master